version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: pg_alx_cache
    restart: unless-stopped
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_alx_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pg_data:
